mouse_hide_wait 0
enable_audio_bell no
confirm_os_window_close 0

# Normal ANSI colors
color0 #475258
color1 #e67e80
color2 #a7c080
color3 #dbbc7f
color4 #7fbbb3
color5 #d699b6
color6 #83c092
color7 #ececee

# Bright ANSI colors
color8 #475258
color9 #e67e80
color10 #a7c080
color11 #dbbc7f
color12 #7fbbb3
color13 #d699b6
color14 #83c092
color15 #ececee

background #181818
foreground #ffffff
