#! /bin/sh

#Autostart
~/.fehbg &
nm-applet &
sxhkd &
picom --config $HOME/.config/picom/picom.conf &


pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8

bspc config border_width        	        3
bspc config window_gap          	        13
bspc config top_padding                   0
bspc config bottom_padding                0
bspc config left_padding                  0
bspc config right_padding                 0
bspc config single_monocle                false
bspc config click_to_focus                true
bspc config split_ratio                   0.50
bspc config borderless_monocle            true
bspc config gapless_monocle               true
bspc config focus_by_distance             true
bspc config focus_follows_pointer         true
bspc config history_aware_focus           true
bspc config remove_disabled_monitors      true
bspc config merge_overlapping_monitors    true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

#### BSPWM coloring ####
bspc config normal_border_color		      "#7A8478"
bspc config active_border_color	       	      "#101313"
bspc config focused_border_color	      "#A7C080"
bspc config presel_feedback_color	      "#008ce3"
bspc config urgent_border_color 	      "#E67E80"

